import { GitHubRepository } from "@/lib/githubJourney";

export const githubJourneyContent = {
  username: "ankitsharma745",
  displayName: "Ankit Sharma",
  developerTitle: "Software developer building polished product systems and AI-era workflows.",
  eyebrow: "GitHub Journey",
  heading: "GitHub Journey",
  intro:
    "A live profile dashboard for public code, repository momentum, and contribution consistency.",
  followLabel: "Follow on GitHub",
  profileFallbackBio:
    "Building production-grade portfolio systems, developer tooling, and business software.",
  snapshotPath: "/data/github-journey.json",
  featuredRepositoryNames: ["portfolio", "pos-desktop"],
  metrics: {
    totalContributions: "Total Contributions",
    currentStreak: "Current Streak",
    longestStreak: "Longest Streak",
    totalRepositories: "Total Repositories",
    followers: "Followers",
    following: "Following",
  },
  repositoryShowcaseTitle: "Repository Showcase",
  contributionActivityTitle: "Contribution Activity",
  timelineTitle: "Developer Journey",
  generatedLabel: "Data synced",
  lastUpdatedLabel: "Last updated",
  unavailableLabel: "Sync pending",
} as const;

export const TOP_GITHUB_REPOSITORY: GitHubRepository[] =[
    {
      fullName: "AnkitSharma745/Monitoring.Log",
      name: "Monitoring.Log",
      description: "A next-generation desktop application designed to monitor, analyze, and diagnose large log files using AI-assisted workflows and local-first architecture.",
      htmlUrl: "https://github.com/AnkitSharma745/Monitoring.Log",
      language: "TypeScript",
      techStack: ["Electron", "React",],
      stars: 120,
      forks: 15,
      isFork: false,
      updatedAt: "2024-06-14T00:00:00Z",
      pushedAt: "2024-06-14T00:00:00Z",
      createdAt: "2024-06-14T00:00:00Z",
      isArchived: false,
    },
    {
      fullName: "AnkitSharma745/portfolio",
      name: "portfolio",
      description: "A content-driven portfolio platform showcasing engineering capabilities, projects, blogs, and AI-era workflows with discoverability in mind.",
      htmlUrl: "https://github.com/AnkitSharma745/portfolio",
      language: "TypeScript",
      techStack: ["Next.js", "Tailwind", "MDX"],
      stars: 85,
      forks: 12,
      isFork: false,
      updatedAt: "2024-05-20T00:00:00Z",
      pushedAt: "2024-05-20T00:00:00Z",
      createdAt: "2024-05-20T00:00:00Z",
      isArchived: false,
    },
    {
      fullName: "AnkitSharma745/ecommerce-kiosk-app",
      name: "ecommerce-kiosk-app",
      description: "A production-grade desktop application powering retail vending machines with a seamless shopping experience, offline capabilities, and hardware integrations.",
      htmlUrl: "https://github.com/AnkitSharma745/ecommerce-kiosk-app",
      language: "TypeScript",
      techStack: ["Electron", "React", "SignalR"],
      stars: 45,
      forks: 5,
      isFork: false,
      updatedAt: "2023-11-01T00:00:00Z",
      pushedAt: "2023-11-01T00:00:00Z",
      createdAt: "2023-11-01T00:00:00Z",
      isArchived: false,
    },
]
